const BASE_URL = 'https://duck1437.shop/front-assess';
const ACTIVE_LOGIN_KEY = 'rdc_active_login';
const TAB_ID_KEY = 'rdc_tab_id';
const LOGIN_HISTORY_KEY = 'rdc_login_history';
const COMMENT_DRAFT_KEY_PREFIX = 'rdc_comment_draft_';
const PUBLISH_AUTOSAVE_KEY_PREFIX = 'rdc_publish_autosave_';
const CHAT_PINNED_KEY_PREFIX = 'rdc_chat_pinned_';
const CHAT_DELETED_KEY_PREFIX = 'rdc_chat_deleted_';
const CHAT_REVOKED_KEY_PREFIX = 'rdc_chat_revoked_';
const MESSAGE_READ_KEY_PREFIX = 'rdc_message_read_';
const MESSAGE_UNREAD_POLL_INTERVAL = 20000;
const PUBLISH_DEFAULT_TOPICS = ['日常', '校园', '学习', '前端', '生活', '美食', '旅行', '摄影', '编程', 'RDC', '考核'];

const routes = {
    '/login': 'page-login',
    '/home': 'page-home',
    '/post-detail': 'page-post-detail',
    '/publish': 'page-publish',
    '/search': 'page-search',
    '/search-result': 'page-search-result',
    '/topic': 'page-topic',
    '/profile': 'page-profile',
    '/drafts': 'page-drafts',
    '/settings': 'page-settings',
    '/messages': 'page-messages',
    '/chat-list': 'page-chat-list',
    '/chat': 'page-chat'
};

const state = {
    currentRoute: '/login',
    isLogin: false,
    recommendPosts: [],
    recommendLastPostId: 0,
    recommendLimit: 10,
    homeHasLoaded: false,
    homeScrollTop: 0,
    currentPostDetail: null,
    detailSwiperIndex: 0,
    detailSwiperTimer: null,
    detailSwiperImageCount: 0,
    postAuthorMap: {},
    postOwnerMap: {},
    currentProfileUser: null,
    profilePosts: [],
    searchRecommendList: [],
    searchRecommendExpanded: false,
    searchResultData: null,
    searchResultTab: 'all',
    searchResultSort: 'latest',
    searchResultContentType: 'all',
    searchResultVisibleCount: 6,
    searchResultPageSize: 6,
    currentSearchKeyword: '',
    searchHistoryList: [],
    publishImageUrls: [],
    commentList: [],
    currentCommentSortType: 1,
    currentReplyParentId: 0,
    currentReplyToUserId: 0,
    currentReplyToUserName: '',
    commentChildMap: {},
    detailIsLiked: false,
    detailIsFavored: false,
    detailAuthorIsFollowing: false,
    favoriteStatusMap: {},
    likedStatusMap: {},
    likedPostIds: [],
    favoritedPostIds: [],
    profileLikedPosts: [],
    profileFavoritedPosts: [],
    profileIsFollowing: false,
    profileFollowingCount: 0,
    profileFollowerCount: 0,
    profileLikeCount: 0,
    profilePostCount: 0,
    profileFollowingIds: [],
    profileFollowerIds: [],
    homeFollowingIds: [],
    followPosts: [],
    draftList: [],
    currentDraftId: '',
    currentEditingPostId: '',
    isRecommendLoadingMore: false,
    hasMoreRecommendPosts: true,
    recommendScrollThreshold: 120,
    lastRecommendLoadTime: 0,
    followVisibleCount: 0,
    followPageSize: 5,
    hasMoreFollowPosts: true,
    isFollowLoadingMore: false,
    messageList: [],
    followMessageList: [],
    likeMessageList: [],
    commentMessageList: [],
    commentLikeMessageList: [],
    followUnreadCount: 0,
    likeUnreadCount: 0,
    commentUnreadCount: 0,
    commentLikeUnreadCount: 0,
    messageUnreadPollTimer: null,
    isUnreadPolling: false,
    chatHistoryList: [],
    currentChatUserId: '',
    chatPinnedUserIds: [],
    chatDeletedUserIds: [],
    chatRevokedMessageIds: [],
    pendingDeleteChatUserId: '',
    chatSocket: null,
    settingsEditVisible: false,
    currentTopicName: '',
    topicPostList: [],
    currentProfileTab: 'posts',
    profileTabScrollMap: {
        posts: 0,
        likes: 0,
        favorites: 0
    },
};
